# Generated by Django 3.2.7 on 2021-12-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=100)),
                ('Productprice', models.IntegerField(default=0)),
                ('Productdescription', models.CharField(default='', max_length=200)),
                ('Productimage', models.ImageField(upload_to='assests/')),
            ],
        ),
    ]
